name: Building and scanning Docker images

on:
    push:
        branches:
            - master
            - CCL-8872
jobs:
    build-scan:
        uses: Home-Office-Digital/core-cloud-workflow-docker-actions/blob/.github/workflows/build-scan-push.yml@1.3.0
        with:
            working_directory: "."
            dockerfile: "Dockerfile"
            image_name: "hof-feedback-form"
            image_tag: "latest"
            tag_latest: true
        secrets:
            AWS_ECR_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
            ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}